(function installCoreCheckGroups(){
  if (window.__coreCheckGroupsV9) return;
  window.__coreCheckGroupsV9 = true;

  var openAreas = {};
  var openChecks = {};
  var ocrLoaderPromise = null;
  var icon = {
    check: '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20 6L9 17l-5-5"/></svg>',
    camera: '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 8h4l2-3h4l2 3h4v11H4z"/><circle cx="12" cy="13" r="4"/></svg>',
    upload: '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 16V4"/><path d="M7 9l5-5 5 5"/><path d="M5 14v5h14v-5"/></svg>',
    group: '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 5h16v4H4zM4 10h16v4H4zM4 15h16v4H4z"/></svg>'
  };
  var style=document.createElement('style');
  style.id='check-photo-viewer-and-ocr-fix-v9';
  style.textContent='.checkPhotoThumb{position:relative!important}.checkPhotoThumb:not(.empty){cursor:pointer!important}.checkPhotoThumb img{display:block!important;width:100%!important;height:100%!important;object-fit:cover!important}.checkPhotoRemove{position:absolute!important;top:8px!important;right:8px!important;width:34px!important;height:34px!important;min-width:34px!important;min-height:34px!important;max-width:34px!important;max-height:34px!important;border-radius:999px!important;border:0!important;padding:0!important;margin:0!important;background:#d0ad58!important;color:#050607!important;font-size:24px!important;font-weight:950!important;line-height:1!important;display:flex!important;align-items:center!important;justify-content:center!important;box-shadow:0 8px 20px rgba(0,0,0,.35)!important}.checkPhotoViewer{position:fixed!important;inset:0!important;z-index:3000!important;background:rgba(0,0,0,.88)!important;display:flex!important;align-items:center!important;justify-content:center!important;padding:18px!important;box-sizing:border-box!important}.checkPhotoViewer img{max-width:100%!important;max-height:100%!important;border-radius:18px!important;object-fit:contain!important;box-shadow:0 18px 50px rgba(0,0,0,.45)!important}.checkPhotoViewerClose{position:fixed!important;top:max(16px,env(safe-area-inset-top))!important;right:16px!important;width:44px!important;height:44px!important;min-width:44px!important;min-height:44px!important;max-width:44px!important;max-height:44px!important;border-radius:999px!important;border:0!important;padding:0!important;margin:0!important;background:rgba(12,15,18,.92)!important;color:#fff!important;font-size:30px!important;line-height:1!important;display:flex!important;align-items:center!important;justify-content:center!important;box-shadow:0 10px 28px rgba(0,0,0,.4)!important}.tempReadStatus{display:block!important;margin-top:8px!important;color:#d0ad58!important;font-weight:800!important}.temperatureCheckPanel input[name="temperature"].ocrFilled{outline:none!important;box-shadow:none!important}.temperatureInputBox:has(input.ocrFilled){outline:none!important;box-shadow:none!important}';
  document.head.appendChild(style);

  function escx(value){try{return esc(value);}catch(_){return String(value==null?'':value).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}}
  function todaySafe(){try{return today();}catch(_){return new Date().toISOString().slice(0,10);}}
  function uidSafe(){try{return uid();}catch(_){return 'id-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2);}}
  function currentUserId(){return state.currentUser||'unknown';}
  function userName(){try{var u=me();return u.nickname||u.name||'Current user';}catch(_){return 'Current user';}}
  function saveSafe(){try{save();}catch(_){} }
  function defaultTemperatureUnits(){return ['Kitchen Fridge 1','Kitchen Fridge 2','Kitchen Freezer','Bar Bottle Fridge','Cellar Fridge'];}
  function genericFridgeCheck(check){var text=String((check.id||'')+' '+(check.title||'')).toLowerCase();return !check.equipmentUnit&&(/fridge.*freezer|freezer.*fridge|fridge-freezer/.test(text));}
  function ensureEquipmentChecks(){state.temperatureUnits=Array.isArray(state.temperatureUnits)&&state.temperatureUnits.length?state.temperatureUnits:defaultTemperatureUnits();state.checks=state.checks||[];var generic=state.checks.find(genericFridgeCheck);var template=generic||{area:'Kitchen',freq:'Daily',due:'11:00'};state.temperatureUnits.forEach(function(unit){var id='temp-'+unit.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');if(!state.checks.some(function(check){return check.id===id;})){state.checks.push({id:id,title:unit+' Temperature Check',area:template.area||'Kitchen',freq:template.freq||'Daily',due:template.due||'11:00',equipmentUnit:unit,checkType:'temperature',items:['Temperature recorded','Photo evidence uploaded','Corrective action recorded if required']});}});state.checks.forEach(function(check){if(genericFridgeCheck(check))check.hiddenFromChecksPage=true;});saveSafe();}
  function doneToday(checkId){return (state.done||[]).some(function(done){return done.checkId===checkId&&done.date===todaySafe();});}
  function isAdminNow(){try{return typeof isAdminUser==='function'&&isAdminUser();}catch(_){return false;}}
  function isTempCheck(check){var text=String((check&&check.checkType||'')+' '+(check&&check.title||'')+' '+((check&&check.items)||[]).join(' ')).toLowerCase();return !!(check&&check.requiresTemperature)||/temp|temperature|fridge|freezer|hot held|cooked|reheated|cooling|delivery/.test(text);}
  function checkCaps(check){var temp=isTempCheck(check);var doc=!!(check&&check.hasDocumentUpload)||((check&&check.checkType)==='document')||!!(check&&check.requiresEvidence&&!temp);var tick=!!(check&&check.hasTickItems);if(check&&typeof check.hasTickItems==='boolean')tick=check.hasTickItems;else tick=!!(!temp&&!doc&&check&&check.items&&check.items.length);return{tick:tick,document:doc,temperature:temp};}
  function dueOnAssignedSchedule(check){var freq=String(check.freq||'Daily');var now=new Date();var days=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];if(freq==='Weekly'&&check.assignedWeeklyDay)return days[now.getDay()]===check.assignedWeeklyDay;if(freq==='Monthly'&&check.assignedMonthlyDate)return String(now.getDate())===String(check.assignedMonthlyDate);return true;}
  function visibleToCurrentUser(check){if(!check.assignedUserId)return true;if(check.assignedUserId===currentUserId())return true;return isAdminNow();}
  function dueChecks(){ensureEquipmentChecks();return (state.checks||[]).filter(function(check){return !check.hiddenFromChecksPage&&!doneToday(check.id)&&visibleToCurrentUser(check)&&dueOnAssignedSchedule(check);});}
  function grouped(list){var groups={};list.forEach(function(check){var area=check.area||'General';(groups[area]=groups[area]||[]).push(check);});return groups;}
  function readFile(file){return new Promise(function(resolve){if(!file)return resolve(null);var reader=new FileReader();reader.onload=function(){resolve({fileName:file.name||'Photo',fileType:file.type||'',fileSize:file.size||0,fileData:reader.result||'',uploadedAt:new Date().toISOString()});};reader.onerror=function(){resolve(null);};reader.readAsDataURL(file);});}
  function preprocessImage(file){return new Promise(function(resolve){if(!file)return resolve(null);var img=new Image();var url=URL.createObjectURL(file);img.onload=function(){try{var maxW=1600;var scale=Math.min(1,maxW/img.width);var w=Math.max(1,Math.round(img.width*scale));var h=Math.max(1,Math.round(img.height*scale));var canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;var ctx=canvas.getContext('2d',{willReadFrequently:true});ctx.drawImage(img,0,0,w,h);var data=ctx.getImageData(0,0,w,h);for(var i=0;i<data.data.length;i+=4){var grey=data.data[i]*0.299+data.data[i+1]*0.587+data.data[i+2]*0.114;var high=grey>150?255:(grey<75?0:grey);data.data[i]=data.data[i+1]=data.data[i+2]=high;}ctx.putImageData(data,0,0);URL.revokeObjectURL(url);resolve(canvas.toDataURL('image/png'));}catch(_){URL.revokeObjectURL(url);resolve(file);}};img.onerror=function(){URL.revokeObjectURL(url);resolve(file);};img.src=url;});}
  function normaliseTempCandidate(value){var m=String(value||'').replace(/\s+/g,'').replace(',','.');var n=parseFloat(m);return !isNaN(n)&&n>-50&&n<100?m:'';}
  function extractTemp(text){var cleaned=String(text||'').replace(/[Oo]/g,'0').replace(/[lI|]/g,'1').replace(/—|–/g,'-').replace(/[·•]/g,'.');var decimal=cleaned.match(/-?\d+\s*[\.,]\s*\d+/);if(decimal){var d=normaliseTempCandidate(decimal[0]);if(d)return d;}var zeroSpace=cleaned.match(/(-?)\b0\s+(\d)\b/);if(zeroSpace)return (zeroSpace[1]||'')+'0.'+zeroSpace[2];var matches=cleaned.match(/-?\d+/g)||[];if(!matches.length)return'';for(var i=0;i<matches.length;i++){var raw=matches[i];if(/^-?0\d$/.test(raw)){return (raw.charAt(0)==='-'?'-':'')+'0.'+raw.replace('-','').charAt(1);}var candidate=normaliseTempCandidate(raw);if(candidate)return candidate;}return'';}
  function loadTesseract(){if(window.Tesseract)return Promise.resolve(window.Tesseract);if(ocrLoaderPromise)return ocrLoaderPromise;ocrLoaderPromise=new Promise(function(resolve,reject){var script=document.createElement('script');var timer=setTimeout(function(){reject(new Error('OCR load timeout'));},15000);script.src='https://cdn.jsdelivr.net/npm/tesseract.js@5/dist/tesseract.min.js';script.async=true;script.onload=function(){clearTimeout(timer);window.Tesseract?resolve(window.Tesseract):reject(new Error('OCR unavailable'));};script.onerror=function(){clearTimeout(timer);reject(new Error('OCR failed to load'));};document.head.appendChild(script);});return ocrLoaderPromise;}
  function withTimeout(promise,ms){return new Promise(function(resolve,reject){var done=false;var timer=setTimeout(function(){if(!done){done=true;reject(new Error('OCR timeout'));}},ms);promise.then(function(value){if(!done){done=true;clearTimeout(timer);resolve(value);}},function(error){if(!done){done=true;clearTimeout(timer);reject(error);}});});}
  function recogniseTemp(Tesseract,image){return withTimeout(Tesseract.recognize(image,'eng',{tessedit_char_whitelist:'0123456789.-,',tessedit_pageseg_mode:'7'}),30000).then(function(result){return result&&result.data&&result.data.text||'';});}
  function maybeReadTemperature(file,input,status){if(!file||!input)return;var fromName=extractTemp(file.name||'');if(fromName&&!input.value){input.value=fromName;input.classList.add('ocrFilled');}if(status)status.textContent='Image uploaded. Analysing image...';loadTesseract().then(function(Tesseract){return preprocessImage(file).then(function(processed){return recogniseTemp(Tesseract,file).catch(function(){return'';}).then(function(rawText){var rawFound=extractTemp(rawText);if(rawFound)return rawFound;return recogniseTemp(Tesseract,processed||file).then(extractTemp);});});}).then(function(found){if(found){input.value=found;input.classList.add('ocrFilled');}if(status)status.textContent=found?'Image uploaded. Temperature auto-filled — check it before saving.':'Image uploaded. Could not read temperature — type it manually before saving.';}).catch(function(){if(status)status.textContent='Image uploaded. Could not read temperature — type it manually before saving.';});}
  function thumb(checkId){return '<div class="checkPhotoThumb empty" data-check-thumb="'+escx(checkId)+'">No photo</div>';}
  function photoPreviewHtml(dataUrl){return '<img src="'+dataUrl+'" alt="Temperature evidence"><button type="button" class="checkPhotoRemove" data-remove-check-photo="true" aria-label="Remove image">×</button>';}
  function openPhotoViewer(src){if(!src)return;var existing=document.querySelector('.checkPhotoViewer');if(existing)existing.remove();var viewer=document.createElement('div');viewer.className='checkPhotoViewer';viewer.innerHTML='<button type="button" class="checkPhotoViewerClose" aria-label="Close image">×</button><img src="'+src+'" alt="Uploaded check photo full view">';document.body.appendChild(viewer);var close=function(){viewer.remove();};viewer.querySelector('.checkPhotoViewerClose').onclick=close;viewer.onclick=function(event){if(event.target===viewer)close();};}
  function tickPanel(check){var items=check.items&&check.items.length?check.items:['Completed'];return '<div class="checkDocItems">'+items.map(function(item,index){return '<label class="checkDocTick"><input type="checkbox" name="task_'+index+'" required><span>'+escx(item)+'</span></label>';}).join('')+'</div>';}
  function documentPanel(check){var note=check.documentNote?'<p class="fdocInstruction">'+escx(check.documentNote)+'</p>':'';return '<div class="checkCompletionDocPanel">'+note+'<div class="fdocBody"><div class="fdocThumb empty" data-evidence-thumb="'+escx(check.id)+'">No document</div><div class="fdocControls"><div class="fdocUploads"><label>'+icon.upload+'<span>Choose File</span><input type="file" name="evidence" accept="image/*,.pdf,.doc,.docx,.png,.jpg,.jpeg"></label><label>'+icon.camera+'<span>Take Photo</span><input type="file" name="evidencePhoto" accept="image/*" capture="environment"></label></div><div class="fdocMeta"><label class="fdocSwitch"><span class="fdocSwitchText">Does Not<br>Expire</span><input type="checkbox" name="documentNoExpiry"><span class="fdocSwitchTrack"></span></label><label class="fdocExpiry"><span class="fdocDateInputWrap"><span class="fdocExpiryText">Expiry Date</span><input type="date" name="documentExpiry"></span></label></div></div></div><small class="checkEvidenceFileName">No file selected</small></div>';}
  function tempPanel(check){return '<div class="temperatureCheckPanel"><p class="temperatureInstruction">Take a photo, confirm the reading, and save.</p><div class="temperatureMainRow">'+thumb(check.id)+'<div class="temperatureSideControls"><label class="temperaturePhotoButton">'+icon.camera+'<span>Take Photo</span><input type="file" name="photo" accept="image/*" capture="environment" required></label><div class="temperatureEntryRow"><label class="temperatureInputBox"><input name="temperature" inputmode="decimal" placeholder="Temp" required><span>°C</span></label><button type="submit" class="temperatureSaveButton">Save</button></div></div></div><small class="tempReadStatus" aria-live="polite"></small></div>';}
  function assignmentOptions(selected){return '<option value="" '+(!selected?'selected':'')+'>Everyone</option>'+(state.users||[]).map(function(u){return '<option value="'+escx(u.id)+'" '+(u.id===selected?'selected':'')+'>'+escx(u.nickname||u.name)+'</option>';}).join('');}
  function assignmentPanel(check){if(!isAdminNow())return'';var weekly=check.assignedWeeklyDay||'Monday';var monthly=check.assignedMonthlyDate||'1';return '<section class="checkAssignmentPanel"><label><span>Assign Staff Member</span><select name="assignedUserId" data-check-assignment>'+assignmentOptions(check.assignedUserId)+'</select></label><label data-check-weekly '+(check.freq==='Weekly'?'':'hidden')+'><span>Day of week</span><select name="assignedWeeklyDay" data-check-assignment>'+['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'].map(function(day){return '<option '+(day===weekly?'selected':'')+'>'+day+'</option>';}).join('')+'</select></label><label data-check-monthly '+(check.freq==='Monthly'?'':'hidden')+'><span>Date of month</span><select name="assignedMonthlyDate" data-check-assignment>'+Array.from({length:31},function(_,i){return String(i+1);}).map(function(day){return '<option '+(day===String(monthly)?'selected':'')+'>'+day+'</option>';}).join('')+'</select></label></section>';}
  function commonPanel(check){return '<label class="actionRequiredInline"><input type="checkbox" name="actionRequired"><span>Corrective action required</span></label><div class="correctiveActionBox"><label><span>Corrective action taken</span><textarea name="correctiveAction" placeholder="Write what was wrong and what was done to fix it"></textarea></label></div><div class="checkSaveRow"><label><span>Notes</span><input name="notes" placeholder="Optional note"></label></div>'+assignmentPanel(check)+'<button class="primary checkSavePrimary" type="submit">Save</button>';}
  function checkPanel(check){var caps=checkCaps(check);return (caps.document?documentPanel(check):'')+(caps.temperature?tempPanel(check):'')+(caps.tick?tickPanel(check):'')+commonPanel(check);}
  function checkCard(check){var open=!!openChecks[check.id];var subtitle=(check.equipmentUnit?check.equipmentUnit+' · ':'')+(check.freq||'')+' · Due '+(check.due||'');return '<article class="fdoc areaCheckCard '+(open?'open':'')+'" data-area-check="'+escx(check.id)+'"><button type="button" class="fdocBar areaCheckToggle" data-toggle-check="'+escx(check.id)+'" aria-expanded="'+(open?'true':'false')+'"><span class="fdocIcon">'+icon.check+'</span><span class="fdocName"><strong>'+escx(check.title)+'</strong><em>'+escx(subtitle)+'</em></span><span class="fdocArrow">⌄</span></button><div class="fdocPanel '+(open?'':'closed')+'"><form class="areaCheckForm" data-check-form="'+escx(check.id)+'">'+checkPanel(check)+'</form></div></article>';}
  checks=window.checks=function checksPage(){openAreas={};var list=dueChecks();var groups=grouped(list);var keys=Object.keys(groups).sort();return '<section class="card checksPage"><h2>Checks to complete</h2><section class="areaGroupList">'+(keys.length?keys.map(function(area){var open=false;return '<section class="areaGroup '+(open?'open':'')+'" data-area-group="'+escx(area)+'"><button type="button" class="fdocBar areaGroupButton" data-toggle-area="'+escx(area)+'" aria-expanded="'+(open?'true':'false')+'"><span class="fdocIcon">'+icon.group+'</span><span class="fdocName"><strong>'+escx(area)+'</strong><em>'+groups[area].length+' checks to complete</em></span><span class="fdocArrow">⌄</span></button><div class="areaGroupBody '+(open?'':'closed')+'">'+groups[area].map(checkCard).join('')+'</div></section>';}).join(''):'<div class="emptyState">No checks currently due.</div>')+'</section></section><section class="card"><h2>Completed today</h2>'+history()+'</section>';};
  function saveAssignment(form){if(!form||!isAdminNow())return;var checkId=form.getAttribute('data-check-form');var check=(state.checks||[]).find(function(item){return item.id===checkId;});if(!check)return;var data=new FormData(form);var assignedUserId=String(data.get('assignedUserId')||'');if(assignedUserId)check.assignedUserId=assignedUserId;else delete check.assignedUserId;check.assignedWeeklyDay=String(data.get('assignedWeeklyDay')||'Monday');check.assignedMonthlyDate=String(data.get('assignedMonthlyDate')||'1');saveSafe();}
  function syncAssignmentPanel(form){if(!form)return;var checkId=form.getAttribute('data-check-form');var check=(state.checks||[]).find(function(item){return item.id===checkId;})||{};var weekly=form.querySelector('[data-check-weekly]');var monthly=form.querySelector('[data-check-monthly]');if(weekly)weekly.hidden=check.freq!=='Weekly';if(monthly)monthly.hidden=check.freq!=='Monthly';}
  function selectedEvidenceFiles(form){return Array.from(form.querySelectorAll('input[type="file"]')).map(function(input){return input.files&&input.files[0];}).filter(Boolean);}
  function documentEvidenceFiles(form){return ['evidence','evidencePhoto'].map(function(name){var input=form.querySelector('input[name="'+name+'"]');return input&&input.files&&input.files[0];}).filter(Boolean);}
  function completeForm(form){if(!form.checkValidity()){form.reportValidity();return;}var checkId=form.getAttribute('data-check-form');var check=(state.checks||[]).find(function(item){return item.id===checkId;});if(!check)return;saveAssignment(form);var data=new FormData(form);var caps=checkCaps(check);var actionRequired=!!data.get('actionRequired');var correctiveAction=String(data.get('correctiveAction')||'').trim();if(actionRequired&&!correctiveAction){alert('Please record the corrective action taken.');return;}var docFiles=documentEvidenceFiles(form);if(caps.document&&!docFiles.length){alert('Please upload a document or take a photo for this check.');return;}var temp=String(data.get('temperature')||'').trim();var tasks=caps.tick?(check.items&&check.items.length?check.items:['Completed']).map(function(label,index){return{label:label,checked:!!data.get('task_'+index)};}):[];var tempPhotoFile=form.querySelector('input[name="photo"]')&&form.querySelector('input[name="photo"]').files&&form.querySelector('input[name="photo"]').files[0];var files=selectedEvidenceFiles(form);Promise.all(files.map(readFile)).then(function(evidence){return readFile(tempPhotoFile).then(function(tempPhoto){state.done=state.done||[];state.done.push({id:uidSafe(),checkId:check.id,title:check.title,area:check.area||'',equipmentUnit:check.equipmentUnit||'',userId:currentUserId(),userName:userName(),date:todaySafe(),at:new Date().toISOString(),result:'Completed',temperature:temp,notes:String(data.get('notes')||'').trim(),actionRequired:actionRequired,correctiveAction:correctiveAction,documentNoExpiry:!!data.get('documentNoExpiry'),documentExpiry:String(data.get('documentExpiry')||''),evidence:evidence.filter(Boolean),tasks:tasks});if(caps.temperature&&temp){state.temps=state.temps||[];state.temps.push({id:uidSafe(),unit:check.equipmentUnit||check.title,reading:temp,status:'Saved',userId:currentUserId(),created:new Date().toISOString(),photo:tempPhoto});}saveSafe();openChecks[checkId]=false;render();});});}
  function removePhotoFromForm(form){if(!form)return;if(!confirm('Remove image?'))return;var photo=form.querySelector('input[name="photo"]');var thumbEl=form.querySelector('.checkPhotoThumb');var status=form.querySelector('.tempReadStatus');var tempInput=form.querySelector('input[name="temperature"]');if(photo)photo.value='';if(tempInput)tempInput.classList.remove('ocrFilled');if(thumbEl){thumbEl.classList.add('empty');thumbEl.innerHTML='No photo';}if(status)status.textContent='';}
  function handlePhotoSelected(form,file){var thumbEl=form&&form.querySelector('.checkPhotoThumb');var tempInput=form&&form.querySelector('input[name="temperature"]');var status=form&&form.querySelector('.tempReadStatus');if(!file||!thumbEl)return;if(status)status.textContent='Uploading image...';if(tempInput)tempInput.classList.remove('ocrFilled');readFile(file).then(function(data){if(data&&data.fileData){thumbEl.classList.remove('empty');thumbEl.innerHTML=photoPreviewHtml(data.fileData);if(status)status.textContent='Image uploaded. Analysing image...';}});maybeReadTemperature(file,tempInput,status);}
  function toggleArea(btn){var area=btn.getAttribute('data-toggle-area');var section=btn.closest('.areaGroup');var body=section&&section.querySelector('.areaGroupBody');var isOpen=!(section&&section.classList.contains('open'));openAreas[area]=isOpen;if(section)section.classList.toggle('open',isOpen);if(body)body.classList.toggle('closed',!isOpen);btn.setAttribute('aria-expanded',String(isOpen));}
  function toggleCheck(btn){var id=btn.getAttribute('data-toggle-check');var card=btn.closest('.areaCheckCard');var panel=card&&card.querySelector('.fdocPanel');var isOpen=!(card&&card.classList.contains('open'));openChecks[id]=isOpen;if(card)card.classList.toggle('open',isOpen);if(panel)panel.classList.toggle('closed',!isOpen);btn.setAttribute('aria-expanded',String(isOpen));}
  function bindAreaGroups(){document.querySelectorAll('[data-toggle-area]').forEach(function(btn){btn.onclick=function(event){event.preventDefault();event.stopPropagation();toggleArea(btn);};});document.querySelectorAll('[data-toggle-check]').forEach(function(btn){btn.onclick=function(event){event.preventDefault();event.stopPropagation();toggleCheck(btn);};});document.querySelectorAll('[name="actionRequired"]').forEach(function(input){var form=input.closest('form');var box=form&&form.querySelector('.correctiveActionBox');var textarea=box&&box.querySelector('textarea');function sync(){if(!box)return;box.classList.toggle('open',input.checked);if(textarea)textarea.required=input.checked;}input.onchange=sync;sync();});document.querySelectorAll('.areaCheckForm').forEach(function(form){syncAssignmentPanel(form);var photo=form.querySelector('input[name="photo"]');if(photo)photo.onchange=function(){var file=photo.files&&photo.files[0];handlePhotoSelected(form,file);};form.querySelectorAll('input[name="evidence"],input[name="evidencePhoto"]').forEach(function(input){input.onchange=function(){var file=input.files&&input.files[0];var name=form.querySelector('.checkEvidenceFileName');if(name)name.textContent=file?file.name:'No file selected';};});form.querySelectorAll('[data-check-assignment]').forEach(function(input){input.onchange=function(){syncAssignmentPanel(form);saveAssignment(form);};});form.onsubmit=function(event){event.preventDefault();completeForm(form);};});}
  document.addEventListener('click',function(event){var removeBtn=event.target.closest&&event.target.closest('[data-remove-check-photo]');if(removeBtn&&removeBtn.closest('.checksPage')){event.preventDefault();event.stopPropagation();removePhotoFromForm(removeBtn.closest('form'));return;}var thumbImg=event.target.closest&&event.target.closest('.checksPage .checkPhotoThumb:not(.empty) img');if(thumbImg){event.preventDefault();event.stopPropagation();openPhotoViewer(thumbImg.getAttribute('src'));return;}var areaBtn=event.target.closest&&event.target.closest('[data-toggle-area]');if(areaBtn&&areaBtn.closest('.checksPage')){event.preventDefault();event.stopPropagation();toggleArea(areaBtn);return;}var checkBtn=event.target.closest&&event.target.closest('[data-toggle-check]');if(checkBtn&&checkBtn.closest('.checksPage')){event.preventDefault();event.stopPropagation();toggleCheck(checkBtn);}},true);
  document.addEventListener('change',function(event){var action=event.target.closest&&event.target.closest('.checksPage input[name="actionRequired"]');if(action){var form=action.closest('form');var box=form&&form.querySelector('.correctiveActionBox');var textarea=box&&box.querySelector('textarea');if(box)box.classList.toggle('open',action.checked);if(textarea)textarea.required=action.checked;return;}var photo=event.target.closest&&event.target.closest('.checksPage input[name="photo"]');if(photo){var form=photo.closest('form');var file=photo.files&&photo.files[0];var name=form&&form.querySelector('.checkEvidenceFileName');if(name)name.textContent=file?file.name:'No file selected';handlePhotoSelected(form,file);}},true);
  document.addEventListener('submit',function(event){var form=event.target.closest&&event.target.closest('.checksPage .areaCheckForm');if(form){event.preventDefault();event.stopPropagation();completeForm(form);}},true);
  if(typeof bind==='function'&&!bind.__coreCheckGroupsV9){var oldBind=bind;bind=function(){oldBind();bindAreaGroups();};bind.__coreCheckGroupsV9=true;}
})();
