(function(){
  if(window.__completeSettingsHubFixedV7) return;
  window.__completeSettingsHubFixedV7=true;

  var openPermissionGroups = {};
  var openCreatePermission = false;
  var PERMISSION_KEYS = ['checks','documents','logs','users','rota','inspection','settings'];
  var NAMED_ADMINS = ['chip','vicky','rihanna'];

  function h(v){try{return esc(v);}catch(_){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}}
  function id(){try{return uid();}catch(_){return 'id-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2);}}
  function saveSafe(){try{save();}catch(_){} }
  function permLabel(key){var labels={checks:'Checks',documents:'Documents',logs:'Logs',users:'Users',rota:'Rota',inspection:'Inspection',settings:'Settings'};return labels[key]||key;}
  function fieldChecked(form,name){return !!(form && form.elements && form.elements[name] && form.elements[name].checked);}
  function userSearchText(u){return String((u&&u.name||'')+' '+(u&&u.nickname||'')+' '+(u&&u.email||'')).toLowerCase();}
  function isNamedAdminUser(u){var text=userSearchText(u);return NAMED_ADMINS.some(function(name){return text.indexOf(name)!==-1;});}

  function ensureSettingsState(){state.permissionMatrix=state.permissionMatrix||{};var defaults={Admin:{checks:true,documents:true,logs:true,users:true,rota:true,inspection:true,settings:true},Supervisor:{checks:true,documents:true,logs:true,users:true,rota:true,inspection:true,settings:true},Staff:{checks:true,documents:false,logs:true,users:false,rota:true,inspection:false,settings:false}};Object.keys(defaults).forEach(function(group){state.permissionMatrix[group]=state.permissionMatrix[group]||{};PERMISSION_KEYS.forEach(function(key){if(typeof state.permissionMatrix[group][key]!=='boolean')state.permissionMatrix[group][key]=!!defaults[group][key];});});(state.users||[]).forEach(function(user){if(isNamedAdminUser(user)){user.permissionSetId='Admin';user.role='Admin';return;}if(!user.permissionSetId)user.permissionSetId=user.role||'Staff';if(!state.permissionMatrix[user.permissionSetId])user.permissionSetId='Staff';user.role=user.permissionSetId;});state.staffDocRequirements=state.staffDocRequirements||[{id:id(),group:'All staff',title:'Right to Work evidence',requiresExpiry:false,notes:'Required before employment begins.'},{id:id(),group:'All staff',title:'Fire Safety Training record',requiresExpiry:true,notes:'Refreshed yearly.'}];state.documentCategories=state.documentCategories||['Licensing','Food Safety','Fire Safety','Health & Safety','Staff','Equipment'];}
  function userCanAccessSettings(){var u=null;try{u=me();}catch(_){u=null;}if(!u)return false;if(isNamedAdminUser(u))return true;var role=String(u.role||'').toLowerCase();if(role.indexOf('admin')!==-1||role.indexOf('supervisor')!==-1||role.indexOf('manager')!==-1)return true;var setName=u.permissionSetId||u.role||'Staff';var matrix=state&&state.permissionMatrix&&state.permissionMatrix[setName];if(matrix&&matrix.settings===true)return true;var lower=String(setName||'').toLowerCase();return lower.indexOf('admin')!==-1||lower.indexOf('supervisor')!==-1||lower.indexOf('manager')!==-1;}
  try{isAdminUser=function(){ensureSettingsState();return userCanAccessSettings();};}catch(_){}

  function actionRow(title,meta,count,actions){return '<article class="settingsActionRow"><div class="settingsActionMain"><strong>'+h(title)+'</strong><em>'+h(meta||'')+'</em>'+(count?'<span>'+h(count)+'</span>':'')+'</div><div class="settingsActionButtons">'+actions+'</div></article>';}
  function groupUsers(group){return (state.users||[]).filter(function(user){return (user.permissionSetId||user.role||'Staff')===group;});}
  function usersDetails(users){return '<details class="permissionUsersDrop"><summary><span class="permissionSummaryText">Select users</span><span class="permissionUserCount">'+users.length+'</span><span class="permissionDetailArrow">⌄</span></summary><div class="permissionUserList">'+(state.users||[]).map(function(user){var assigned=users.some(function(u){return u.id===user.id;});return '<label class="settingsTick permissionUserTick"><input type="checkbox" name="user__'+h(user.id)+'" '+(assigned?'checked':'')+'><span><strong>'+h(user.nickname||user.name)+'</strong><em>'+h(user.name||'')+'</em></span></label>';}).join('')+'</div></details>';}
  function permissionButton(group){var open=!!openPermissionGroups[group];var p=state.permissionMatrix[group]||{};var users=groupUsers(group);return '<article class="permissionGroupCard '+(open?'open':'')+'" data-permission-card="'+h(group)+'"><button type="button" class="fdocBar permissionGroupButton" data-toggle-permission-group="'+h(group)+'" aria-expanded="'+(open?'true':'false')+'"><span class="fdocIcon">✓</span><span class="fdocName"><strong>'+h(group)+'</strong><em>'+users.length+' users · '+PERMISSION_KEYS.filter(function(k){return p[k];}).length+' permissions enabled</em></span><span class="fdocArrow">⌄</span></button><div class="permissionGroupPanel '+(open?'':'closed')+'"><form class="permissionGroupForm" data-permission-group-form="'+h(group)+'"><div class="permissionTickList"><h3>Permissions</h3>'+PERMISSION_KEYS.map(function(key){return '<label class="settingsTick permissionTick"><input type="checkbox" name="perm__'+h(key)+'" '+(p[key]?'checked':'')+'><span>'+h(permLabel(key))+'</span></label>';}).join('')+'</div>'+usersDetails(users)+'<div class="permissionActions"><button type="button" class="secondary" data-open-users-tab="true">Open Users tab</button><button class="primary">Save permissions</button></div></form></div></article>';}
  function createPermissionGroup(){var open=openCreatePermission;return '<article class="permissionGroupCard createPermissionCard '+(open?'open':'')+'"><button type="button" class="fdocBar permissionGroupButton" data-toggle-create-permission="true" aria-expanded="'+(open?'true':'false')+'"><span class="fdocIcon">+</span><span class="fdocName"><strong>Create permissions group</strong><em>Create a new title, permissions and starting users</em></span><span class="fdocArrow">⌄</span></button><div class="permissionGroupPanel '+(open?'':'closed')+'"><form id="createPermissionGroupForm" class="permissionGroupForm"><label class="settingsField"><span>Group title</span><input name="title" placeholder="e.g. Duty Manager" required></label><div class="permissionTickList"><h3>Permissions</h3>'+PERMISSION_KEYS.map(function(key){return '<label class="settingsTick permissionTick"><input type="checkbox" name="perm__'+h(key)+'"><span>'+h(permLabel(key))+'</span></label>';}).join('')+'</div><details class="permissionUsersDrop" open><summary><span class="permissionSummaryText">Select users</span><span class="permissionUserCount">'+(state.users||[]).length+'</span><span class="permissionDetailArrow">⌄</span></summary><div class="permissionUserList">'+(state.users||[]).map(function(user){return '<label class="settingsTick permissionUserTick"><input type="checkbox" name="user__'+h(user.id)+'"><span><strong>'+h(user.nickname||user.name)+'</strong><em>'+h(user.name||'')+'</em></span></label>';}).join('')+'</div></details><button class="primary">Create permissions group</button></form></div></article>';}
  function checkSetup(){return '<section class="settingsBlock"><h2>Checklist setup</h2><p class="muted">Edit built-in checks here. Staff see the clean completion version.</p><div class="settingsActionList">'+(state.checks||[]).map(function(c){return actionRow(c.title,(c.area||'')+' · '+(c.freq||'')+' · Due '+(c.due||''),(c.items||[]).length+' checklist items','<button class="secondary settingsSmallButton" data-edit-check="'+h(c.id)+'">Edit</button><button class="primary settingsSmallButton" data-complete="'+h(c.id)+'">Test</button>');}).join('')+'</div>'+addCheckForm()+'</section>';}
  function addCheckForm(){return '<details class="settingsExpander"><summary><span>Add new checklist</span><small>Create a new recurring check for staff to complete</small></summary><form id="checkForm" class="stack settingsExpanderBody"><input name="title" placeholder="Check title" required><select name="area">'+(state.areas||[]).map(function(a){return '<option>'+h(a)+'</option>';}).join('')+'</select><select name="freq"><option>Daily</option><option>Weekly</option><option>Monthly</option><option>Yearly</option></select><input name="due" type="time" value="12:00" required><textarea name="items" placeholder="One checklist item per line" required></textarea><label class="checkline"><input type="checkbox" name="sign"> Requires manager sign-off</label><button class="primary">Add checklist</button></form></details>';}
  function pubDetails(){return '<section class="settingsBlock"><h2>Pub details</h2><p class="muted">Core premises information used in reports and inspection mode.</p><form id="pubForm" class="stack settingsForm"><input name="name" value="'+h(state.pub&&state.pub.name)+'" placeholder="Pub name"><input name="licence" value="'+h(state.pub&&state.pub.licence)+'" placeholder="Premises licence"><input name="dps" value="'+h(state.pub&&state.pub.dps)+'" placeholder="DPS"><textarea name="address" placeholder="Address">'+h(state.pub&&state.pub.address)+'</textarea><button class="primary">Save pub details</button></form></section>';}
  function permissions(){var roles=Object.keys(state.permissionMatrix||{}).sort(function(a,b){var order={Admin:1,Supervisor:2,Staff:3};return (order[a]||99)-(order[b]||99)||a.localeCompare(b);});return '<section class="settingsBlock permissionSettingsBlock"><h2>Permissions</h2><p class="muted">Each group opens like a check button. Users can only belong to one permissions group at a time.</p><div class="permissionGroupList">'+roles.map(permissionButton).join('')+createPermissionGroup()+'</div></section>';}
  function requiredDocs(){var groups=['All staff','Admin','Supervisor','Staff','FOH','Kitchen','Cellar','Housekeeping','KP','Office'];return '<section class="settingsBlock"><h2>Required staff documents</h2><p class="muted">Set which documents are required for staff groups or job areas.</p><div class="settingsActionList">'+(state.staffDocRequirements||[]).map(function(r){return actionRow(r.title,r.group+(r.requiresExpiry?' · expiry required':' · no expiry required'),r.notes||'','<button class="secondary settingsSmallButton" data-delete-staff-doc-req="'+h(r.id)+'">Remove</button>');}).join('')+'</div><details class="settingsExpander"><summary><span>Add required staff document</span><small>Assign a required document to a role or work group</small></summary><form id="staffDocReqForm" class="stack settingsExpanderBody"><select name="group">'+groups.map(function(g){return '<option>'+h(g)+'</option>';}).join('')+'</select><input name="title" placeholder="Document title" required><label class="checkline"><input type="checkbox" name="requiresExpiry"> Requires expiry date</label><textarea name="notes" placeholder="Notes / examples / requirement details"></textarea><button class="primary">Add requirement</button></form></details></section>';}
  function documentSetup(){return '<section class="settingsBlock"><h2>Document categories</h2><p class="muted">Manage the categories used by premises and staff documents.</p><ul class="plainList settingsSimpleList">'+(state.documentCategories||[]).map(function(c){return '<li><span>'+h(c)+'</span></li>';}).join('')+'</ul><form id="documentCategoryForm" class="inlineForm settingsInline"><input name="category" placeholder="New category" required><button class="primary">Add category</button></form></section>'+(typeof documents==='function'?'<section class="settingsBlock"><h2>Premises documents</h2>'+documents()+'</section>':'');}
  function areas(){return '<section class="settingsBlock"><h2>Areas / sections</h2><p class="muted">Used for checks, user profiles and rota sections.</p><ul class="plainList settingsSimpleList">'+(state.areas||[]).map(function(a){return '<li><span>'+h(a)+'</span><button class="secondary settingsSmallButton" data-delete-area="'+h(a)+'">Remove</button></li>';}).join('')+'</ul><form id="areaForm" class="inlineForm settingsInline"><input name="area" placeholder="New area / section" required><button class="primary">Add area</button></form></section>';}
  function rotaSetup(){var sections=((state.rotaSettings||{}).sections)||[];return '<section class="settingsBlock"><h2>Rota setup</h2><p class="muted">Shared setup for rota sections and future rota integration.</p><ul class="plainList settingsSimpleList">'+sections.map(function(s){return '<li><span>'+h(s)+'</span></li>';}).join('')+'</ul><form id="rotaSectionForm" class="inlineForm settingsInline"><input name="section" placeholder="New rota section" required><button class="primary">Add rota section</button></form></section>';}
  window.settings=function(){ensureSettingsState();if(!userCanAccessSettings())return '<section class="card"><h2>Settings unavailable</h2><p>Only admin/supervisor users can change settings.</p></section>';return '<section class="hero card settingsHero"><div><p class="eyebrow">Admin only</p><h2>Settings</h2><p>All adjustable setup and premises information for this pub.</p></div></section><section class="settingsHub">'+pubDetails()+permissions()+requiredDocs()+checkSetup()+documentSetup()+areas()+rotaSetup()+'</section>';};
  function togglePermissionCard(btn,isCreate){var card=btn.closest('.permissionGroupCard');var panel=card&&card.querySelector('.permissionGroupPanel');var isOpen=!(card&&card.classList.contains('open'));if(isCreate){openCreatePermission=isOpen;}else{var group=btn.getAttribute('data-toggle-permission-group');openPermissionGroups[group]=isOpen;}if(card)card.classList.toggle('open',isOpen);if(panel)panel.classList.toggle('closed',!isOpen);btn.setAttribute('aria-expanded',String(isOpen));}
  function bindCompleteSettings(){document.querySelectorAll('[data-toggle-permission-group]').forEach(function(btn){btn.onclick=function(ev){if(ev){ev.preventDefault();ev.stopPropagation();}togglePermissionCard(btn,false);};});document.querySelectorAll('[data-toggle-create-permission]').forEach(function(btn){btn.onclick=function(ev){if(ev){ev.preventDefault();ev.stopPropagation();}togglePermissionCard(btn,true);};});document.querySelectorAll('[data-open-users-tab]').forEach(function(btn){btn.onclick=function(){route='staff';render();};});document.querySelectorAll('[data-permission-group-form]').forEach(function(form){form.onsubmit=function(ev){ev.preventDefault();var group=form.getAttribute('data-permission-group-form');state.permissionMatrix[group]=state.permissionMatrix[group]||{};PERMISSION_KEYS.forEach(function(key){state.permissionMatrix[group][key]=fieldChecked(form,'perm__'+key);});(state.users||[]).forEach(function(user){if(isNamedAdminUser(user)){user.permissionSetId='Admin';user.role='Admin';return;}if(fieldChecked(form,'user__'+user.id)){user.permissionSetId=group;user.role=group;}else if((user.permissionSetId||user.role)===group){user.permissionSetId='Staff';user.role='Staff';}});saveSafe();render();};});var create=document.getElementById('createPermissionGroupForm');if(create)create.onsubmit=function(ev){ev.preventDefault();var title=String(create.elements.title.value||'').trim();if(!title){return;}if(state.permissionMatrix[title]){alert('A permissions group with that title already exists.');return;}state.permissionMatrix[title]={};PERMISSION_KEYS.forEach(function(key){state.permissionMatrix[title][key]=fieldChecked(create,'perm__'+key);});(state.users||[]).forEach(function(user){if(isNamedAdminUser(user)){user.permissionSetId='Admin';user.role='Admin';return;}if(fieldChecked(create,'user__'+user.id)){user.permissionSetId=title;user.role=title;}});openPermissionGroups[title]=true;openCreatePermission=false;saveSafe();render();};}
  if(typeof bind==='function'&&!bind.__completeSettingsHubFixedV7){var old=bind;bind=function(){old();bindCompleteSettings();};bind.__completeSettingsHubFixedV7=true;}
  ensureSettingsState();saveSafe();
})();
