(function(){
  if(window.__completeSettingsHub) return;
  window.__completeSettingsHub=true;

  function h(v){try{return esc(v);}catch(_){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}}
  function id(){try{return uid();}catch(_){return 'id-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2);}}
  function ensureSettingsState(){
    state.permissionMatrix=state.permissionMatrix||{
      Admin:{checks:true,documents:true,logs:true,users:true,rota:true,settings:true},
      Supervisor:{checks:true,documents:true,logs:true,users:true,rota:true,settings:true},
      Staff:{checks:true,documents:false,logs:true,users:false,rota:true,settings:false}
    };
    state.staffDocRequirements=state.staffDocRequirements||[
      {id:id(),group:'All staff',title:'Right to Work evidence',requiresExpiry:false,notes:'Required before employment begins.'},
      {id:id(),group:'All staff',title:'Fire Safety Training record',requiresExpiry:true,notes:'Refreshed yearly.'}
    ];
    state.documentCategories=state.documentCategories||['Licensing','Food Safety','Fire Safety','Health & Safety','Staff','Equipment'];
  }
  function actionRow(title,meta,count,actions){return '<article class="settingsActionRow"><div class="settingsActionMain"><strong>'+h(title)+'</strong><em>'+h(meta||'')+'</em>'+(count?'<span>'+h(count)+'</span>':'')+'</div><div class="settingsActionButtons">'+actions+'</div></article>';}
  function checkSetup(){
    return '<section class="settingsBlock"><h2>Checklist setup</h2><p class="muted">Edit built-in checks here. Staff see the clean completion version.</p><div class="settingsActionList">'+(state.checks||[]).map(function(c){return actionRow(c.title,(c.area||'')+' · '+(c.freq||'')+' · Due '+(c.due||''),(c.items||[]).length+' checklist items','<button class="secondary settingsSmallButton" data-edit-check="'+h(c.id)+'">Edit</button><button class="primary settingsSmallButton" data-complete="'+h(c.id)+'">Test</button>');}).join('')+'</div>'+addCheckForm()+'</section>';
  }
  function addCheckForm(){return '<details class="settingsExpander"><summary><span>Add new checklist</span><small>Create a new recurring check for staff to complete</small></summary><form id="checkForm" class="stack settingsExpanderBody"><input name="title" placeholder="Check title" required><select name="area">'+(state.areas||[]).map(function(a){return '<option>'+h(a)+'</option>';}).join('')+'</select><select name="freq"><option>Daily</option><option>Weekly</option><option>Monthly</option><option>Yearly</option></select><input name="due" type="time" value="12:00" required><textarea name="items" placeholder="One checklist item per line" required></textarea><label class="checkline"><input type="checkbox" name="sign"> Requires manager sign-off</label><button class="primary">Add checklist</button></form></details>';}
  function pubDetails(){return '<section class="settingsBlock"><h2>Pub details</h2><p class="muted">Core premises information used in reports and inspection mode.</p><form id="pubForm" class="stack settingsForm"><input name="name" value="'+h(state.pub&&state.pub.name)+'" placeholder="Pub name"><input name="licence" value="'+h(state.pub&&state.pub.licence)+'" placeholder="Premises licence"><input name="dps" value="'+h(state.pub&&state.pub.dps)+'" placeholder="DPS"><textarea name="address" placeholder="Address">'+h(state.pub&&state.pub.address)+'</textarea><button class="primary">Save pub details</button></form></section>';}
  function permissions(){var roles=['Admin','Supervisor','Staff'];var areas=['checks','documents','logs','users','rota','settings'];return '<section class="settingsBlock"><h2>Permissions</h2><p class="muted">Control what each user role can access. These are app-level settings for this pub.</p><form id="permissionForm" class="settingsPermissionGrid">'+roles.map(function(role){var p=state.permissionMatrix[role]||{};return '<fieldset><legend>'+h(role)+'</legend>'+areas.map(function(a){return '<label class="settingsTick"><input type="checkbox" name="'+h(role)+'__'+h(a)+'" '+(p[a]?'checked':'')+'> <span>'+h(a.charAt(0).toUpperCase()+a.slice(1))+'</span></label>';}).join('')+'</fieldset>';}).join('')+'<button class="primary">Save permissions</button></form></section>';}
  function requiredDocs(){var groups=['All staff','Admin','Supervisor','Staff','FOH','Kitchen','Cellar','Housekeeping','KP','Office'];return '<section class="settingsBlock"><h2>Required staff documents</h2><p class="muted">Set which documents are required for staff groups or job areas.</p><div class="settingsActionList">'+(state.staffDocRequirements||[]).map(function(r){return actionRow(r.title,r.group+(r.requiresExpiry?' · expiry required':' · no expiry required'),r.notes||'','<button class="secondary settingsSmallButton" data-delete-staff-doc-req="'+h(r.id)+'">Remove</button>');}).join('')+'</div><details class="settingsExpander"><summary><span>Add required staff document</span><small>Assign a required document to a role or work group</small></summary><form id="staffDocReqForm" class="stack settingsExpanderBody"><select name="group">'+groups.map(function(g){return '<option>'+h(g)+'</option>';}).join('')+'</select><input name="title" placeholder="Document title" required><label class="checkline"><input type="checkbox" name="requiresExpiry"> Requires expiry date</label><textarea name="notes" placeholder="Notes / examples / requirement details"></textarea><button class="primary">Add requirement</button></form></details></section>';}
  function documentSetup(){return '<section class="settingsBlock"><h2>Document categories</h2><p class="muted">Manage the categories used by premises and staff documents.</p><ul class="plainList settingsSimpleList">'+(state.documentCategories||[]).map(function(c){return '<li><span>'+h(c)+'</span></li>';}).join('')+'</ul><form id="documentCategoryForm" class="inlineForm settingsInline"><input name="category" placeholder="New category" required><button class="primary">Add category</button></form></section>'+(typeof documents==='function'?'<section class="settingsBlock"><h2>Premises documents</h2>'+documents()+'</section>':'');}
  function areas(){return '<section class="settingsBlock"><h2>Areas / sections</h2><p class="muted">Used for checks, user profiles and rota sections.</p><ul class="plainList settingsSimpleList">'+(state.areas||[]).map(function(a){return '<li><span>'+h(a)+'</span><button class="secondary settingsSmallButton" data-delete-area="'+h(a)+'">Remove</button></li>';}).join('')+'</ul><form id="areaForm" class="inlineForm settingsInline"><input name="area" placeholder="New area / section" required><button class="primary">Add area</button></form></section>';}
  function rotaSetup(){var sections=((state.rotaSettings||{}).sections)||[];return '<section class="settingsBlock"><h2>Rota setup</h2><p class="muted">Shared setup for rota sections and future rota integration.</p><ul class="plainList settingsSimpleList">'+sections.map(function(s){return '<li><span>'+h(s)+'</span></li>';}).join('')+'</ul><form id="rotaSectionForm" class="inlineForm settingsInline"><input name="section" placeholder="New rota section" required><button class="primary">Add rota section</button></form></section>';}
  window.settings=function(){
    if(typeof isAdminUser==='function'&&!isAdminUser()) return '<section class="card"><h2>Settings unavailable</h2><p>Only admin/supervisor users can change settings.</p></section>';
    ensureSettingsState();
    return '<section class="hero card settingsHero"><div><p class="eyebrow">Admin only</p><h2>Settings</h2><p>All adjustable setup and premises information for this pub.</p></div></section><section class="settingsHub">'+pubDetails()+permissions()+requiredDocs()+checkSetup()+documentSetup()+areas()+rotaSetup()+'</section>';
  };
  if(typeof bind==='function'&&!bind.__completeSettingsHub){var old=bind;bind=function(){old();bindCompleteSettings();};bind.__completeSettingsHub=true;}
  function bindCompleteSettings(){
    var pf=document.getElementById('permissionForm');if(pf)pf.onsubmit=function(ev){ev.preventDefault();['Admin','Supervisor','Staff'].forEach(function(role){state.permissionMatrix[role]=state.permissionMatrix[role]||{};['checks','documents','logs','users','rota','settings'].forEach(function(a){state.permissionMatrix[role][a]=!!pf.elements[role+'__'+a]?.checked;});});save();render();};
    var sf=document.getElementById('staffDocReqForm');if(sf)sf.onsubmit=function(ev){ev.preventDefault();var d=Object.fromEntries(new FormData(sf).entries());state.staffDocRequirements=state.staffDocRequirements||[];state.staffDocRequirements.push({id:id(),group:d.group,title:d.title,requiresExpiry:!!sf.elements.requiresExpiry.checked,notes:d.notes||''});save();render();};
    document.querySelectorAll('[data-delete-staff-doc-req]').forEach(function(btn){btn.onclick=function(){state.staffDocRequirements=(state.staffDocRequirements||[]).filter(function(r){return r.id!==btn.getAttribute('data-delete-staff-doc-req');});save();render();};});
    var cf=document.getElementById('documentCategoryForm');if(cf)cf.onsubmit=function(ev){ev.preventDefault();var d=Object.fromEntries(new FormData(cf).entries());if(d.category&&!(state.documentCategories||[]).includes(d.category)){state.documentCategories.push(d.category);}save();render();};
  }
  setTimeout(function(){ensureSettingsState();try{save();}catch(_){}},0);
})();